### ISSUE TITLE
Keyboard Backlight cannot be adjusted. Turns off automatically upon sleep and display off.

### ISSUE THREAD

**Issue by adrian21456** [doanhmaple/Asus-TUF-Gaming-FX505GE-Hackintosh#1]
Good Day. First of all, I am really grateful for your guide. I actually successfully installed on my laptop hackintosh. I have the same laptop as you and the only problem is the keyboar backlight. Is there anyway to remap the Fn+Up or Fn+Down Keys. Thank you so much. I appreciate your effort a lot.

**Comment by doanhxd** [comment]
use Karabiner to map them. ty
